Repository prefeitura-rio/pipelines_rj_sms, pull requests merged in 2025-08, with the labels that each got.

#435 [CDI] Atualiza rodapé; comunica erros de extração
  pipelines/datalake/extract_load/gal_gcs/flows.py
  pipelines/datalake/extract_load/gal_gcs/tasks.py
  pipelines/datalake/migrate/orquestracao_cdi/flows.py
  pipelines/datalake/migrate/orquestracao_cdi/tasks.py
  pipelines/datalake/migrate/orquestracao_cdi/utils.py
  pipelines/flows.py
Labels: ready-to-merge

#442 [CDI] Nova demanda: link DO se voto TCM; texto rodapé
  pipelines/datalake/migrate/orquestracao_cdi/tasks.py
  pipelines/datalake/migrate/orquestracao_cdi/utils.py
Labels: ready-to-merge

#425 [Vitacare Historico] Refatoração Flow
  localrun.cases.yaml
  pipelines/datalake/extract_load/vitacare_historico/constants.py
  pipelines/datalake/extract_load/vitacare_historico/flows.py
  pipelines/datalake/extract_load/vitacare_historico/schedules.py
  pipelines/datalake/extract_load/vitacare_historico/tasks.py
  pipelines/datalake/extract_load/vitacare_historico/utils.py
  pipelines/flows.py
Labels: conflict, ready-to-merge

#449 fix: Conserta dockerfile (apt-key → gpg)
  Dockerfile
Labels: ready-to-merge

#454 fix: GCS → CloudSQL
  localrun.cases.yaml
  pipelines/datalake/migrate/gcs_to_cloudsql/flows.py
  pipelines/datalake/migrate/gcs_to_cloudsql/tasks.py
  pipelines/datalake/migrate/gcs_to_cloudsql/utils.py
Labels: ready-to-merge

#462 [Projeto CDI] - Extração do Diário Oficial da União pela API do INLABS
  localrun.cases.yaml
  pipelines/datalake/extract_load/diario_oficial_uniao_api/constants.py
  pipelines/datalake/extract_load/diario_oficial_uniao_api/flows.py
  pipelines/datalake/extract_load/diario_oficial_uniao_api/schedules.py
  pipelines/datalake/extract_load/diario_oficial_uniao_api/tasks.py
  pipelines/flows.py
Labels: conflict
