Repository prefeitura-rio/pipelines_rj_sms, pull requests merged in 2025-07, with the labels that each got.

#337 [HCI] Rastreio de pacientes restritos
  localrun.cases.yaml
  pipelines/datalake/extract_load/tpc_azure_blob/tasks.py
  pipelines/datalake/transform/gemini/pacientes_restritos/constants.py
  pipelines/datalake/transform/gemini/pacientes_restritos/flows.py
  pipelines/datalake/transform/gemini/pacientes_restritos/schedules.py
  pipelines/datalake/transform/gemini/pacientes_restritos/tasks.py
  pipelines/flows.py
  pipelines/utils/tasks.py
Labels: conflict

#362 Extração Diário Oficial: reestruturação
  pipelines/datalake/extract_load/diario_oficial_rj/flows.py
  pipelines/datalake/extract_load/diario_oficial_rj/logica.txt
  pipelines/datalake/extract_load/diario_oficial_rj/regras.txt
  pipelines/datalake/extract_load/diario_oficial_rj/schedules.py
  pipelines/datalake/extract_load/diario_oficial_rj/tasks.py
  pipelines/datalake/extract_load/diario_oficial_rj/utils.py
Labels: ready-to-merge

#405 [Cientifica Lab] Handle Error Upload To Datalake
  localrun.cases.yaml
  pipelines/datalake/extract_load/cientificalab_api/flows.py
  pipelines/datalake/extract_load/cientificalab_api/tasks.py
  pipelines/utils/tasks.py
Labels: ready-to-merge

#393 [MEDLAB]
  localrun.cases.yaml
  pipelines/datalake/extract_load/medilab_api/constants.py
  pipelines/datalake/extract_load/medilab_api/flows.py
  pipelines/datalake/extract_load/medilab_api/tasks.py
  pipelines/datalake/extract_load/medilab_api/utils.py
  pipelines/flows.py
Labels: conflict

#416 [CDI] fix: `str(case_num.strip())` → `str(case_num).strip()`
  pipelines/datalake/migrate/orquestracao_cdi/schedules.py
  pipelines/datalake/migrate/orquestracao_cdi/utils.py
Labels: ready-to-merge

#417 [CDI] Ajustes orquestrador
  pipelines/datalake/migrate/orquestracao_cdi/tasks.py
  pipelines/flows.py
Labels: dont-merge

#418 [CDI] feat: recipientes dinâmicos (via Sheets)
  pipelines/datalake/migrate/orquestracao_cdi/flows.py
  pipelines/datalake/migrate/orquestracao_cdi/tasks.py
Labels: ready-to-merge

#420 [CDI] Retentativa na tabela de destinatários
  pipelines/datalake/migrate/orquestracao_cdi/constants.py
  pipelines/datalake/migrate/orquestracao_cdi/tasks.py
Labels: ready-to-merge

#430 [CDI] Muda horário para teste
  pipelines/datalake/migrate/orquestracao_cdi/schedules.py
Labels: ready-to-merge

#428 [CDI: DO-RJ] Implementa tabela de status
  pipelines/datalake/extract_load/diario_oficial_rj/flows.py
  pipelines/datalake/extract_load/diario_oficial_rj/tasks.py
  pipelines/datalake/extract_load/diario_oficial_rj/utils.py
  pipelines/datalake/extract_load/tribunal_de_contas_rj/flows.py
  pipelines/datalake/migrate/orquestracao_cdi/flows.py
Labels: ready-to-merge
